import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NbEvaIconsModule } from '@nebular/eva-icons';
import { NbThemeModule, NbLayoutModule, NbIconModule, NbUserModule, NbSidebarModule, NbMenuModule, NbInputModule,
  NbListModule, NbCardModule, NbButtonModule, NbTreeGridModule, NbSpinnerModule, NbSelectModule, NbAlertModule,
  NbToastrModule, NbAutocompleteModule, NbButtonGroupModule, NbStepperModule, NbDialogModule, NbCheckboxModule, NbActionsModule, NbContextMenuModule, NbBadgeModule } from '@nebular/theme';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    NbThemeModule.forRoot({ name: 'default' }),
    NbSidebarModule.forRoot(),
    NbSidebarModule,
    NbMenuModule.forRoot(),
    NbMenuModule,
    NbToastrModule.forRoot(),
    NbDialogModule.forRoot(),
    NbLayoutModule,
    NbEvaIconsModule,
    NbIconModule,
    NbUserModule,
    NbInputModule,
    NbCardModule,
    NbButtonModule,
    NbListModule,
    NbTreeGridModule,
    NbSpinnerModule,
    NbSelectModule,
    NbAlertModule,
    NbAutocompleteModule,
    NbButtonGroupModule,
    NbStepperModule,
    NbCheckboxModule,
    NbActionsModule,
    NbContextMenuModule,
    NbBadgeModule,

  ],
  exports: [
    CommonModule,
    NbSidebarModule,
    NbMenuModule,
    NbLayoutModule,
    NbEvaIconsModule,
    NbIconModule,
    NbUserModule,
    NbInputModule,
    NbCardModule,
    NbButtonModule,
    NbListModule,
    NbTreeGridModule,
    NbSpinnerModule,
    NbSelectModule,
    NbAlertModule,
    NbAutocompleteModule,
    NbButtonGroupModule,
    NbStepperModule,
    NbCheckboxModule,
    NbActionsModule,
    NbContextMenuModule,
    NbBadgeModule,
  ]
})
export class NebularComponentModule { }
